In [1]:
from bs4 import BeautifulSoup
import requests, lxml

# heritage foundation
# nytimes.com
# foxnews.com
# ACLU

In [2]:
r = requests.get('https://www.heritage.org/gender')

In [3]:
r

In [4]:
source_code = r.content

In [5]:
soup = BeautifulSoup(source_code, 'html.parser')

In [6]:
soup.title

In [7]:
# always check an element in the body, to see that the scrape worked

soup.p

## the `soup` object

In [125]:
#### the soup object

# attributes: title, h1, .text
# methods: find(), find_all()

# you can access items as attributes or via methods

In [8]:
## accessing elements as ATTRIBUTES

soup.h1

<h1>
<div>Gender</div>
</h1>

In [126]:
## accessing elements with METHODS

# using the inspector to find the headlines

soup.find('div', class_ = 'result-card__info-wrapper')

<div class="result-card__info-wrapper">
<a class="result-card__title js-hover-target" href="/education/commentary/restoring-single-sex-education-vmi-and-beyond" title="article link">Restoring Single-Sex Education at VMI and Beyond</a>
<a class="result-card__link" href="/staff/scott-yenor-phd" title="article link"> <span>Scott  Yenor, PhD</span>
</a> <p class="result-card__date"><span>Oct 21, 2025</span>   7 min read
</p>
</div>

In [127]:
## narrowing down our data

# into inner elements, getting the title

soup.find('a', class_ = 'result-card__title')

In [128]:
# narrowing down, into inner elements, getting the date

soup.find('p', class_ = 'result-card__date')

<p class="result-card__date"><span>Oct 21, 2025</span>   7 min read
</p>

In [129]:
# narrowing down, into inner elements, getting just the text

soup.find('a', class_ = 'result-card__title').text

'Restoring Single-Sex Education at VMI and Beyond'

## individual challenge

In [130]:
### CHALLENGE:

# look for just the author's name

soup.find('a', class_ = 'result-card__link').text.strip()

'Scott  Yenor, PhD'

## looping through elements to extract data

In [9]:
### looping through elements to pull out information about each one
#   - create a variable to hold the item you're looping through
#   - use find_all() to create the variable

articles = soup.find_all('div', class_ = 'result-card__info-wrapper') 

for i in articles[:3]: 
    print(i)

<div class="result-card__info-wrapper">
<a class="result-card__title js-hover-target" href="/education/commentary/restoring-single-sex-education-vmi-and-beyond" title="article link">Restoring Single-Sex Education at VMI and Beyond</a>
<a class="result-card__link" href="/staff/scott-yenor-phd" title="article link"> <span>Scott  Yenor, PhD</span>
</a> <p class="result-card__date"><span>Oct 21, 2025</span>   7 min read
</p>
</div>
<div class="result-card__info-wrapper">
<a class="result-card__title js-hover-target" href="/gender/commentary/patients-treated-better-because-doctors-skill-not-gender-identity" title="article link">Patients Treated Better Because of Doctors’ Skill, Not Gender Identity</a>
<a class="result-card__link" href="/staff/jonathan-butcher" title="article link"> <span>Jonathan  Butcher</span>
</a> <p class="result-card__date"><span>Oct 6, 2025</span>   3 min read
</p>
</div>
<div class="result-card__info-wrapper">
<a class="result-card__title js-hover-target" href="/the-constitution/commentary/ubers-new-women-preferences-program-violates-civil-rights-law" title="article link">Uber’s New “Women Preferences” Program Violates Civil Rights Law</a>
<p class="result-card__date"><span>Aug 8, 2025</span>   4 min read
</p>
</div>

In [10]:
# pull out: 
# - title
# - date 

## -> will need to layer the elements to get the date.

for i in articles[:3]: 
    print(i.a.text)
    print(i.p.span.text)

Restoring Single-Sex Education at VMI and Beyond
Oct 21, 2025
Patients Treated Better Because of Doctors’ Skill, Not Gender Identity
Oct 6, 2025
Uber’s New “Women Preferences” Program Violates Civil Rights Law
Aug 8, 2025

In [133]:
### GROUP WORK!

# pull out:
# - author

for i in articles[:3]: 
    print(i.a.text)
    print(i.p.span.text)
    print(i.span.text)

Restoring Single-Sex Education at VMI and Beyond
Oct 21, 2025
Scott  Yenor, PhD
Patients Treated Better Because of Doctors’ Skill, Not Gender Identity
Oct 6, 2025
Jonathan  Butcher
Uber’s New “Women Preferences” Program Violates Civil Rights Law
Aug 8, 2025
Aug 8, 2025

## saving our data to lists

To review, here is the process for extracting elements from a webpage, now with the added step of saving to a CSV file:

multiple steps:
1. choose element that contains all data you want: titles, date, tags,...
2. note the html structure of data: which elements are contained within which elements?
3. write code that picks out the information we want from the data
4. process information into lists
5. save to CSV

In [11]:
titles = []
dates = []
authors = []

for i in articles: 
    titles.append(i.a.text)
    if i.p.span is not None:
        date = i.p.span.text
    else:
        date = 'Nd'
    dates.append(date)
    authors.append(i.span.text)

In [12]:
dates

['Oct 21, 2025',
 'Oct 6, 2025',
 'Aug 8, 2025',
 'Nd',
 'Mar 20, 2025',
 'Mar 20, 2025',
 'Feb 27, 2025',
 'Feb 19, 2025']

## finally, saving to CSV

In [13]:
import pandas as pd

df = pd.DataFrame({
    'date': dates,
    'title': titles,
    'author': authors
})

In [14]:
df

,date,title,author
0,"Oct 21, 2025",Restoring Single-Sex Education at VMI and Beyond,"Scott Yenor, PhD"
1,"Oct 6, 2025",Patients Treated Better Because of Doctors’ Sk...,Jonathan Butcher
2,"Aug 8, 2025",Uber’s New “Women Preferences” Program Violate...,"Aug 8, 2025"
3,Nd,States Must Refuse to Define “Abuse” as Raisin...,"Apr 16, 2025"
4,"Mar 20, 2025","Sorry Democrats, but Trump’s “Two Sexes” Execu...",Sarah Parshall Perry
5,"Mar 20, 2025",Tyrants of the Imperious Judiciary: Federal Ju...,Hans A. von Spakovsky
6,"Feb 27, 2025",Follow the Law,Sarah Parshall Perry
7,"Feb 19, 2025",Trump’s Transgender Orders Are Well Within Exe...,"Feb 19, 2025"

In [15]:
df.to_csv('heritage.csv')

## a couple of possibilities:
- we might continue to gather more articles by paginating through the URLs manually.
- we might start to filter through the dataset, maybe we are only interested in articles about China.

In [140]:
# first, create a soup of the next page

r = requests.get('https://www.heritage.org/big-tech?taxonomy_term_tid=143&page=1')
source = r.content
soup = BeautifulSoup(source, 'html.parser')

In [141]:
# then, loop through the articles and save the info we want to lists

# be careful to change the list name here, you don't want to overwrite articles
articles1 = soup.find_all('div', class_ = 'result-card__info-wrapper') 

for i in articles1: 
    titles.append(i.a.text)
    if i.p.span is not None:
        date = i.p.span.text
    else:
        date = 'Nd'
    dates.append(date)
    authors.append(i.span.text)

In [142]:
# re-create the dataframe

df = pd.DataFrame({
    'date': dates,
    'title': titles,
    'author': authors
})

In [143]:
df

,date,title,author
0,"Oct 21, 2025",Restoring Single-Sex Education at VMI and Beyond,"Scott Yenor, PhD"
1,"Oct 6, 2025",Patients Treated Better Because of Doctors’ Sk...,Jonathan Butcher
2,"Aug 8, 2025",Uber’s New “Women Preferences” Program Violate...,"Aug 8, 2025"
3,Nd,States Must Refuse to Define “Abuse” as Raisin...,"Apr 16, 2025"
4,"Mar 20, 2025","Sorry Democrats, but Trump’s “Two Sexes” Execu...",Sarah Parshall Perry
5,"Mar 20, 2025",Tyrants of the Imperious Judiciary: Federal Ju...,Hans A. von Spakovsky
6,"Feb 27, 2025",Follow the Law,Sarah Parshall Perry
7,"Feb 19, 2025",Trump’s Transgender Orders Are Well Within Exe...,"Feb 19, 2025"
8,Nd,Protecting Children from Predatory Social Medi...,Annie Chestnut Tutor
9,Nd,Parents’ Survey: Online Filters and Blocking S...,Annie Chestnut Tutor
10,,Screens & Sickness: Raising Healthy Kids in a ...,
11,"Aug 22, 2025",Good Luck Trying To Leave TikTok,"Aug 22, 2025"
12,"Aug 21, 2025",AI Companions Are Harming Your Children,"Aug 21, 2025"
13,"Aug 15, 2025",We Should Not Be Digital Slaves,Autumn Dorsey
14,"Aug 7, 2025",A Federalist Approach to AI Policy,"Aug 7, 2025"
15,"Jul 30, 2025",Time for States and Congress To Follow Texas i...,Annie Chestnut Tutor

In [144]:
# now, you could even write a loop that automates this for EVERY page!

# range() function to enumerate through pages
# f-string to insert the page number into the requests.get() call
# time.sleep() function to take a couple of seconds pause between each call

# BREAK

## group work: 

Extract some information from another website.

In [16]:
r = requests.get('https://www.aclu.org/news/by-issue/transgender-rights')
source = r.content
soup = BeautifulSoup(source, 'html.parser')

In [17]:
soup.title

In [18]:
soup.text

"\n\n\n\n\n\n\n\nTransgender Rights | American Civil Liberties Union\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSkip navigation\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNews & Commentary about\n            Transgender Rights        \n\n\n\n\n\n                The ACLU works in courts, legislatures, and communities to defend and preserve the individual rights and liberties that the Constitution and the laws of the United States guarantee everyone in this country.            \n\n\n \n\n\n\n\n\n\n \n\nJan 13, 2026\nLive Coverage: West Virginia v. B.P.J. SCOTUS arguments\n\n\nLive Coverage: West Virginia v. B.P.J. SCOTUS arguments\n\n\n\n\n\n \n\nDec 17, 2025\nWhat’s On The Docket: A 2026 SCOTUS Briefing\n\n\nWhat’s On The Docket: A 2026 SCOTUS Briefing\n\n\n\n\n\n \n\nJul 21, 2025\nCourt Strikes Down NIH's Unlawful Termination of Research Grants on Topics Including DEI and Gender Identity\n\n\nCourt Strikes Down NIH's Unlawful Termination of Research Grants on Topics Including DEI and Gender Identity\n\n\n\n\n\n \n\nJun 26, 2025\nThe Supreme Court Dealt A Blow to Trans Rights. Here's How to Take Action\n\n\nThe Supreme Court Dealt A Blow to Trans Rights. Here's How to Take Action\n\n\n\n\n\n \n\nJun 20, 2025\nWho We Fight For: The Journey to Trans Liberation\n\n\nWho We Fight For: The Journey to Trans Liberation\n\n\n\n\n\n \n\nJun 9, 2025\nWhat the Marriage Equality Backlash Taught Me About the Fight for Trans Rights\n\n\nWhat the Marriage Equality Backlash Taught Me About the Fight for Trans Rights\n\n\n\n\n\n \n\nJun 6, 2025\nSkrmetti, Obergefell, and the Path Forward for LGBTQIA+ Rights with Chase Strangio\n\n\nSkrmetti, Obergefell, and the Path Forward for LGBTQIA+ Rights with Chase Strangio\n\n\n\n\n\n \n\nMay 9, 2025\nWe’re Still Ready: Trump’s First 100 Days with Cecillia Wang\n\n\nWe’re Still Ready: Trump’s First 100 Days with Cecillia Wang\n\n\n\n\n\n \n\nApr 3, 2025\nThe Human Toll of Trump's Anti-Trans Crusade\n\n\nThe Human Toll of Trump's Anti-Trans Crusade\n\n\n\n\n\n \n\nFeb 14, 2025\nKnow Your LGBTQ+ Rights with Chase Strangio\n\n\nKnow Your LGBTQ+ Rights with Chase Strangio\n\n\n1\n2\n3\n4\n5\n…\n33\nNext\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n"

In [19]:
soup.find('p', class_ = 'has-font-family-compressed has-text-dark mt-1 is-special-size-30')

In [20]:
soup.find('p', class_ = 'has-font-family-compressed').text

'Live Coverage: West Virginia v. B.P.J. SCOTUS arguments'

In [21]:
h_articles = soup.find_all('div', class_ = 'is-flex-touch')

In [22]:
h_articles[0]

<div class="is-flex-touch is-flex-direction-column is-justify-content-center is-8">
<p class="has-text-weight-bold is-size-6 has-text-navy">Jan 13, 2026</p>
<p class="has-font-family-compressed has-text-dark mt-1 is-special-size-30">Live Coverage: West Virginia v. B.P.J. SCOTUS arguments</p>
</div>

In [23]:
titles = []
dates = []

for i in h_articles: 
    dates.append(i.find('p', class_ = 'has-text-weight-bold').text)
    titles.append(i.find('p', class_ = 'has-font-family-compressed').text)

In [24]:
titles

['Live Coverage: West Virginia v. B.P.J. SCOTUS arguments',
 'What’s On The Docket: A 2026 SCOTUS Briefing',
 "Court Strikes Down NIH's Unlawful Termination of Research Grants on Topics Including DEI and Gender Identity",
 "The Supreme Court Dealt A Blow to Trans Rights. Here's How to Take Action",
 'Who We Fight For: The Journey to Trans Liberation',
 'What the Marriage Equality Backlash Taught Me About the Fight for Trans Rights',
 'Skrmetti, Obergefell, and the Path Forward for LGBTQIA+ Rights with Chase Strangio',
 'We’re Still Ready: Trump’s First 100 Days with Cecillia Wang',
 "The Human Toll of Trump's Anti-Trans Crusade",
 'Know Your LGBTQ+ Rights with Chase Strangio']

In [25]:
dates

['Jan 13, 2026',
 'Dec 17, 2025',
 'Jul 21, 2025',
 'Jun 26, 2025',
 'Jun 20, 2025',
 'Jun 9, 2025',
 'Jun 6, 2025',
 'May 9, 2025',
 'Apr 3, 2025',
 'Feb 14, 2025']